# Generated by Django 5.0.2 on 2024-02-14 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_planner', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vol',
        ),
        migrations.AddField(
            model_name='voyage',
            name='mode_transport',
            field=models.CharField(choices=[('TR', 'Train'), ('AV', 'Avion'), ('VO', 'Voiture')], default='TR', max_length=2),
        ),
        migrations.AddField(
            model_name='voyage',
            name='prix',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
