# Generated by Django 5.0.2 on 2024-02-14 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_planner', '0002_delete_vol_voyage_mode_transport_voyage_prix'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voyage',
            name='date_retour',
        ),
        migrations.RemoveField(
            model_name='voyage',
            name='description',
        ),
        migrations.RemoveField(
            model_name='voyage',
            name='lieu',
        ),
        migrations.AddField(
            model_name='voyage',
            name='date_arrivee',
            field=models.DateTimeField(default='2024-02-15 00:00:00'),
        ),
        migrations.AddField(
            model_name='voyage',
            name='lieu_arrivee',
            field=models.CharField(default="Lieu d'arrivée par défaut", max_length=100),
        ),
        migrations.AddField(
            model_name='voyage',
            name='lieu_depart',
            field=models.CharField(default='Lieu de départ par défaut', max_length=100),
        ),
        migrations.AlterField(
            model_name='voyage',
            name='date_depart',
            field=models.DateTimeField(default='2024-02-14 00:00:00'),
        ),
        migrations.AlterField(
            model_name='voyage',
            name='titre',
            field=models.CharField(default='Titre par défaut', max_length=100),
        ),
    ]
