# Generated by Django 5.0.2 on 2024-02-14 08:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_planner', '0003_remove_voyage_date_retour_remove_voyage_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voyage',
            name='date_arrivee',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 15, 0, 0)),
        ),
        migrations.AlterField(
            model_name='voyage',
            name='date_depart',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 14, 0, 0)),
        ),
    ]
