# Generated by Django 5.0.2 on 2024-02-16 12:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_planner', '0004_alter_voyage_date_arrivee_alter_voyage_date_depart'),
    ]

    operations = [
        migrations.AddField(
            model_name='voyage',
            name='date_retour',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='voyage',
            name='date_arrivee',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='voyage',
            name='date_depart',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
