# Generated by Django 5.0.2 on 2024-02-29 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_planner', '0005_voyage_date_retour_alter_voyage_date_arrivee_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hebergement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('type_hebergement', models.CharField(choices=[('HO', 'Hôtel'), ('AU', 'Auberge'), ('CH', "Chambre d'hôte")], max_length=2)),
                ('adresse', models.CharField(max_length=200)),
                ('prix_nuit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nombre_chambres_disponibles', models.IntegerField(default=0)),
            ],
        ),
    ]
