# Generated by Django 5.0.2 on 2024-02-29 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_planner', '0008_voyage_ville_arrivee_voyage_ville_depart_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hebergement',
            name='ville',
            field=models.CharField(default='ville par defaut', max_length=100),
            preserve_default=False,
        ),
    ]
