# Generated by Django 5.0.2 on 2024-02-12 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('tel', models.CharField(max_length=20)),
                ('mail', models.EmailField(max_length=254)),
                ('date_naissance', models.DateField()),
                ('lieu', models.CharField(max_length=100)),
                ('adresse_rue', models.CharField(max_length=255)),
                ('adresse_ville', models.CharField(max_length=100)),
            ],
        ),
    ]
